[package]
name = "github-auth"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yoshuawuyts/github-auth"
documentation = "https://docs.rs/github-auth"
description = "GitHub authentication for CLIs"
authors = ["Yoshua Wuyts <yoshuawuyts@gmail.com>"]
readme = "README.md"

[dependencies]
dialoguer = "0.1.0"
directories = "0.9.0"
failure = "0.1.1"
mkdirp = "0.1.0"
serde = "1.0.45"
serde_json = "1.0.17"
reqwest = "0.8.5"

[dev-dependencies]
# clippy = "0.0"
